### ISSUE TITLE
closeFindWidget on cursor movement?

### ISSUE THREAD

**Issue by anticrisis** [SebastianZaha/vscode-emacs-friendly#12]
I would like to close the `findWidget` automatically when moving the cursor. This duplicates the way emacs works. For example, I will often do a search with a few `ctrl+s`'s, and then `alt+<` to return to the top of the file. In emacs, this cancels the search operation. But with this extension, the findWidget is still open, which causes some confusion with other commands.

Would this be as straightforward as adding this snippet to the each cursor movement command? Is there a smarter way to do this?

```
            {
                "key": "ctrl+g",  // change to for example alt+<, alt+>, etc.
                "command": "closeFindWidget",
                "when": "editorFocus && findWidgetVisible"
            },
```

**Comment by anticrisis** [comment]
Here's a pull request that gets the job done: https://github.com/SebastianZaha/vscode-emacs-friendly/pull/13

**Comment by SebastianZaha** [comment]
Thanks a lot! Merged and published.

**Comment by dlandis** [comment]
This is a great change ! I'd been meaning to raise an issue about it. Thanks
