### ISSUE TITLE
Typing does not replace selection

### ISSUE THREAD

**Issue by evanbross** [SebastianZaha/vscode-emacs-friendly#35]
Typing new text does not replace selected text.

Is this broken, not yet implemented, a feature, or a configurable option?

**Comment by kyleboyle** [comment]
Could you explain your issue in a little more detail? If I select text with the mouse and type something, the characters are replaced.

**Comment by evanbross** [comment]
Sorry, I think I ended up on the page for the wrong Emacs plugin.
I don't use VS Code, I use traditional VS 2017.

**Comment by kyleboyle** [comment]
Sounds good. If you have no issue to report for this project, would you mark this one resolved? Thanks
