### ISSUE TITLE
Split screen not working.

### ISSUE THREAD

**Issue by joeyJsonar** [SebastianZaha/vscode-emacs-friendly#47]
Split screen involving:

C-x 1 | Close editors in other (split) group.
C-x 2 | Split editor
C-x 3 | Toggle split layout (vertical to horizontal)
C-x o | Focus other split editor

are not working.

**Comment by brother** [comment]
This works perfectly for me. The mappings are not correct though.

C-x 2 should do split down not right.
C-x 3 does a flip instead of split right.

And a shortcut for focus previous would be good. (in emacs I have added C-x p for this)

**Comment by SebastianZaha** [comment]
Fixed mappings in merged pull req today.
