### ISSUE TITLE
ctrl-o open-line

### ISSUE THREAD

**Issue by cleemesser** [SebastianZaha/vscode-emacs-friendly#60]
In emacs I use ctrl-o to open a new line reflexively and the lack of that keybinding causes me no end of frustration in trying to use vscode. 

 I've added this emacs keybinding in pull request #56 and it fixes my particular problem.
(this is my first time trying to add to an extension, so be warned)

**Comment by prayagupd** [comment]
Looks like `C-o` is already added to keybinding for line break. (I m using `Version 1.30.2 (1.30.2)`)

This is what I See in `keybindings.json`

```javascript
{ 
 "key": "ctrl+o",               
 "command": "lineBreakInsert",
 "when": "textInputFocus && !editorReadonly" 
},
```

**Comment by cleemesser** [comment]
Interesting. I have switched to using Awesome Emacs Keymap which has this and other improvements included.

**Comment by SebastianZaha** [comment]
Fixed via merged pull request today.
