### ISSUE TITLE
C-k is incomplete

### ISSUE THREAD

**Issue by vvuk** [SebastianZaha/vscode-emacs-friendly#7]
In emacs, if the point is in a line where point to end of line contains only whitespace (or nothing), the whitespace and the newline will be deleted.  That is, `C-a C-k C-k` will remove the current line entirely, and if a line contains `"abc#      "`, and a next line `"def"` where `#` is the cursor, and `C-k` is hit, the result will be `"abcdef"` with point on the `d`.

`vscode-emacs` had.. something.. at some point, e.g. https://github.com/SebastianZaha/vscode-emacs-friendly/blob/248d42753fe02771adb38e691c734fdb4453cf01/src/operation.ts#L72 but it also wasn't quite correct.

**Comment by SebastianZaha** [comment]
Thanks for reporting, this will be fixed when we finish https://github.com/SebastianZaha/vscode-emacs-friendly/pull/5

**Comment by yoni-tock** [comment]
I also ran into this. If there's anything I can do to help, lmk!

**Comment by SebastianZaha** [comment]
Merged and published fix for this finally.
