### ISSUE TITLE
Toggle Zen Mode [Ctrl+K Z] does not work

### ISSUE THREAD

**Issue by JohnRyanAudio** [SebastianZaha/vscode-emacs-friendly#8]
For me, this key command just inserts a 'z' into the text. I use zen mode all the the time, so having to open with mouse from menu slows me down.

**Comment by SebastianZaha** [comment]
Aha, this happens because Ctrl+k is the kill command in emacs. I have rebound zen toggle to C+x z (instead of C+k). This is published already, should work when you will update the extension.
